### PR TITLE
Cleaning up duplicate test

### PR DESCRIPTION
**Pull request by dr-rodriguez**
Cleaning up a duplicated test in test_integrity.py

### CODE REVIEW

**Comment by kelle** [comment]
Even though these two tests kind of do the same thing, they do it differently. (When I wrote them, I remember thinking that they are technically different.)  I don't mind having extra tests since the different approaches could theoretically find weird things. Is there any good reason to delete it? It's not very resource intensive.

**Comment by dr-rodriguez** [comment]
My main reason was to clean up duplicated code. At some point we may have tons of tests and having two (or more) that do the same thing is probably not idea. At the moment, you're right- it's not particularly resource intensive. 
An alternative could be to have the two independent checks being handled by the same test_source_uniqueness function (ie, two assert statements in that single call).

**Comment by kelle** [comment]
I like the idea of two asserts in one test! I didn't know you could do that. I guess both asserts need to pass in order for the test to pass?

**Comment by dr-rodriguez** [comment]
Correct. Though if the first assert fails, any subsequent ones are not checked which is one drawback of that setup.

**Comment by kelle** [comment]
I like that compromise. Can you revise the PR?

**Pull request merged**
